trigger:
- main   # or your working branch

pool:
  name: 'agent_ayesha'                             # your agent pool
  demands:
    - agent.name -equals agent_ayesha_linux       # run only on this agent

stages:
- stage: Build
  jobs:
  - job: MavenBuild
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        publishJUnitResults: true
        testResultsFiles: '/surefire-reports/TEST-*.xml'

- stage: PushArtifact
  dependsOn: Build
  jobs:
  - job: PublishToArtifacts
    steps:
    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'maven-archetype-webapps'   # Replace with your Azure Artifacts feed name

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'deploy'
        options: '-DskipTests'
        publishJUnitResults: false
