trigger:
- main

# Build number format: YYYYMMDD.r
name: $(date:yyyyMMdd)$(rev:.r)

variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml

resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main

jobs:
- job: MavenBuildAndPublish
  displayName: 'Maven Build and Publish JAR'
  pool:
    name: 'agent_ayesha'               # Your agent pool
    demands:
      - agent.name -equals agent_ayesha_linux   # Run only on this agent

  steps:
  # Step 1: Checkout repo
  - checkout: self
    clean: true
    fetchTags: false

  # Step 2: Run Maven build
  - task: Maven@4
    displayName: 'Build with Maven (pom.xml)'
    inputs:
      mavenPOMFile: $(BuildParameters.mavenPOMFile)
      goals: 'clean package'

  # Step 3: Copy built JAR files to staging directory
  - task: CopyFiles@2
    displayName: 'Copy JAR Files to: $(Build.ArtifactStagingDirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: 'Amazon-Core/target'
      Contents: '**/*.jar'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  # Step 4: Publish the JARs as artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
