#clupped 3, 4, 5 questions all
trigger:
- main

pool:
  name: 'agent_ayesha'
  demands:
    - agent.name -equals agent_ayesha_linux

variables:
  mavenPomFile: 'pom.xml'
  dockerRegistryServiceConnection: 'azurecontainerregistrydocker'
  containerRegistry: 'containerregistryksa.azurecr.io'
  imageRepository: 'ksayeshasiddiqaazuredeveopspipelinewithgithubnew'
  imageTag: '$(Build.BuildId)'
  fullImageName: '$(containerRegistry)/$(imageRepository):$(imageTag)'

steps:
# 1. Checkout code
- checkout: self

# 2. Build with Maven
- task: Maven@4
  displayName: 'Build with Maven'
  inputs:
    mavenPomFile: $(mavenPomFile)
    goals: 'clean package'

# 3. Build and push Docker image to ACR
- task: Docker@2
  displayName: 'Build and Push to ACR'
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: '**/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(imageTag)

# 4. Login to ACR
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: login
    containerRegistry: $(dockerRegistryServiceConnection)

# 5. Run and verify container
- script: |
    echo "Pulling image: $(fullImageName)"
    docker pull $(fullImageName)

    echo "Running image..."
    docker run -d --name testcontainer -p 5000:5000 $(fullImageName)

    echo "Check container status"
    docker ps

    echo "Verify container response"
    docker exec testcontainer echo "Container is running successfully!"

    echo "Cleaning up..."
    docker rm -f testcontainer
  displayName: 'Run and Verify Container'
